CREATE TABLE ENTIDADE (
    NIF CHAR(9),
    NOME VARCHAR(50) NOT NULL,
    CONSTRAINT PK_ENTIDADE PRIMARY KEY (NIF)
);

CREATE TABLE CONTRATO (
    ID_CONTRATO INTEGER PRIMARY KEY AUTOINCREMENT,
    DESCRICAO VARCHAR(300),
    DATA DATE NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,
    TIPO VARCHAR(20) NOT NULL
);

CREATE TABLE PRODUTO (
    CPV VARCHAR(150),
    NOME VARCHAR(150) NOT NULL,
    CONSTRAINT PK_PRODUTO PRIMARY KEY (CPV)
);

CREATE TABLE CONTRATO_PRODUTO (
    ID_CONTRATO INTEGER,
    CPV VARCHAR(150),
    CONSTRAINT PK_CONTRATO_PRODUTO PRIMARY KEY (ID_CONTRATO, CPV),
    CONSTRAINT FK_CONTRATO_PRODUTO_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO (ID_CONTRATO),
    CONSTRAINT FK_CONTRATO_PRODUTO_PRODUTO FOREIGN KEY (CPV) REFERENCES PRODUTO (CPV)
);

CREATE TABLE CONTRATO_ENTIDADE (
    ID_CONTRATO INTEGER,
    NIF_ENTIDADE CHAR(9),
    TIPO VARCHAR(20) NOT NULL,
    CONSTRAINT PK_CONTRATO_ENTIDADE PRIMARY KEY (ID_CONTRATO, NIF_ENTIDADE),
    CONSTRAINT FK_CONTRATO_ENTIDADE_CONTRATO FOREIGN KEY (ID_CONTRATO) REFERENCES CONTRATO (ID_CONTRATO),
    CONSTRAINT FK_CONTRATO_ENTIDADE_ENTIDADE FOREIGN KEY (NIF_ENTIDADE) REFERENCES ENTIDADE (NIF)
);